#!/bin/bash
#
# build - compile and optionally install asciigames components
#

build_nethack() {
  #
  # Repo: https://github.com/doctorfree/asciigames
  #
  # Fork of Repo: https://github.com/NetHack/NetHack
  # with bug fixes and enhancements from UnNetHack at
  # https://github.com/UnNetHack/UnNetHack
  #
  # Initial build for NetHack
  # [ -f src/nethack ] || {
  #   sys/unix/setup.sh sys/unix/hints/linux-asciiville
  #   make fetch-lua
  #   make
  #   cd doc
  #   make
  #   cd ..
  # }
  # chmod +x src/nethack
  #
  # Revised build with UnNetHack changes
  [ -f src/nethack ] || {
    cd sys/autoconf
    ./bootstrap.sh
    cd ../..
    chmod 755 configure
    ./configure --prefix=${PREFIX}/games \
                --with-owner=games \
                --with-group=games \
                --enable-wizmode=doctorwhen
    make
  }
  [ "${INSTALL}" ] && sudo PREFIX=${PREFIX} make install
}

build_ninvaders() {
  [ -f cmake_build/ninvaders ] || {
    cmake -B cmake_build
    cmake --build cmake_build -j2
  }
}

build_tetris() {
  [ -f tetris ] || {
    ./configure.sh --prefix=${PREFIX}/games --enable-xlib=no --enable-curses=yes
    make
    make gameserver
  }
  [ "${INSTALL}" ] && sudo make install
}

usage() {
    printf "\nUsage: ./build [-i] [-p prefix] [-u] project [project2 ...]"
    printf "\nWhere:"
    printf "\n\t-i indicates install"
    printf "\n\t-p prefix specifies installation prefix (default ${PREFIX})"
    printf "\n\t-u displays this usage message and exits\n"
    printf "\nNo arguments: build nethack, configure with prefix=${PREFIX}, build\n"
    exit 1
}

arch=
centos=
debian=
fedora=
[ -f /etc/os-release ] && . /etc/os-release
[ "${ID_LIKE}" == "debian" ] && debian=1
[ "${ID}" == "arch" ] || [ "${ID_LIKE}" == "arch" ] && arch=1
[ "${ID}" == "centos" ] && centos=1
[ "${ID}" == "fedora" ] && fedora=1
[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1

if [ "${debian}" ]
then
  PKGS="build-essential libncurses-dev cmake"
  if [ "$1" == "-r" ]
  then
    sudo apt remove ${PKGS}
  else
    sudo apt install ${PKGS} pandoc zip
  fi
else
  if [ "${arch}" ]
  then
    PKGS="base-devel cmake ncurses"
    if [ "$1" == "-r" ]
    then
      sudo pacman -Rs ${PKGS}
    else
      sudo pacman -S --needed ${PKGS} pandoc zip
    fi
  else
    have_dnf=`type -p dnf`
    if [ "${have_dnf}" ]
    then
      PINS=dnf
    else
      PINS=yum
    fi
    sudo ${PINS} makecache
    if [ "${fedora}" ]
    then
      PKGS="cmake ncurses-devel"
      if [ "$1" == "-r" ]
      then
        sudo ${PINS} -y remove ${PKGS}
        sudo ${PINS} -y groupremove "Development Tools" "Development Libraries"
      else
        sudo ${PINS} -y groupinstall "Development Tools" "Development Libraries"
        sudo ${PINS} -y install ${PKGS} pandoc zip
      fi
    else
      if [ "${centos}" ]
      then
        PKGS="cmake ncurses-devel"
        if [ "$1" == "-r" ]
        then
          sudo ${PINS} -y remove ${PKGS}
          sudo ${PINS} -y groupremove "Development Tools"
        else
          sudo ${PINS} -y groupinstall "Development Tools"
          sudo ${PINS} -y install ${PKGS} pandoc zip
        fi
      else
        echo "Unrecognized operating system"
      fi
    fi
  fi
fi

PROJ=nethack
INSTALL=
platform=`uname -s`
if [ "${platform}" == "Darwin" ]
then
  PREFIX=/usr/local
else
  PREFIX=/usr
fi
while getopts "ip:u" flag; do
    case $flag in
        i)
            INSTALL=1
            ;;
        p)
            PREFIX="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

for project in $*
do
  case "${project}" in
    nethack)
      PROJ=nethack
      [ -d ${PROJ} ] && {
        cd ${PROJ}
        build_nethack
        cd ..
      }
      ;;
    ninvaders)
      PROJ=ninvaders
      [ -d ${PROJ} ] && {
        cd ${PROJ}
        build_ninvaders
        cd ..
      }
      ;;
    tetris|vitetris)
      PROJ=tetris
      [ -d ${PROJ} ] && {
        cd ${PROJ}
        build_tetris
        cd ..
      }
      ;;
    *)
      echo "Unsupported project build: ${project}"
      continue
      ;;
  esac
  [ -d ${PROJ} ] || {
    echo "$PROJ does not exist or is not a directory."
    echo "Run: git clone https://github.com/doctorfree/asciigames"
  }
done
