#!/bin/bash

sudo rm -rf dist releases asciigames
cd 2048
make clean
cd ..
cd nethack
[ -f Makefile ] && make spotless
rm -f config.log config.status configure doc/Guidebook.txt \
      sys/share/Makefile.lib sys/autoconf/autoconf.hin \
      util/dgn.tab.h util/lev.tab.h
cd ../tetris
[ -f Makefile ] && make clean
rm -f tetris gameserver src/config.h
cd ../ninvaders
rm -rf cmake_build
